import { useEffect, useState } from 'react'
import { ArrowRight, CheckCircle2, Clock3, GitBranch, RefreshCcw, Search, Server, Users, Workflow } from 'lucide-react'
import type { BranchInfo } from './types'
import { api } from './api/client'
import { Header } from './components/Header'
import { MappingEditor } from './components/MappingEditor'
import { Sidebar } from './components/Sidebar'

type CurrentUser = { id: string; email: string; name: string }
type PageProps = { navigate: (path: string) => void }

function PageHeader({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight text-slate-950">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div>{action}</div> }
function StatCard({ label, value, icon: Icon }: { label: string; value: number | string; icon: typeof Users }) { return <div className="cm-card p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">{value}</p></div><div className="rounded-lg bg-slate-100 p-2.5 text-slate-600"><Icon className="h-5 w-5" /></div></div></div> }
function Info({ label, value, mono }: { label: string; value: any; mono?: boolean }) { return <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs text-slate-400">{label}</p><p className={`mt-1 font-medium text-slate-800 ${mono ? 'font-mono text-sm' : ''}`}>{value}</p></div> }
function Loading() { return <div className="cm-card p-10 text-center text-sm text-slate-500">Loading...</div> }
function Empty({ text }: { text: string }) { return <div className="p-10 text-center text-sm text-slate-500">{text}</div> }
function ErrorBox({ message, onRetry }: { message: string; onRetry?: () => void }) { return <div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{message}{onRetry && <button className="ml-3 font-medium underline" onClick={onRetry}>Retry</button>}</div> }

function DashboardPage() { const [data, setData] = useState<any>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const load = () => { setLoading(true); api.dashboard().then(setData).catch((e) => setError(e.message)).finally(() => setLoading(false)) }; useEffect(load, []); if (loading) return <Loading />; if (error) return <ErrorBox message={error} onRetry={load} />; const s = data.summary; return <><PageHeader title="Dashboard" description="Review the current state of workflow credential mappings and repository activity." action={<button className="cm-btn-secondary" onClick={load}><RefreshCcw className="h-4 w-4" /> Refresh</button>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Teams" value={s.teams} icon={Users} /><StatCard label="Workflows" value={s.workflows} icon={Workflow} /><StatCard label="Mappings" value={s.mappings} icon={GitBranch} /><StatCard label="Drafts" value={s.drafts} icon={Clock3} /></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="cm-card p-5"><div className="mb-5"><h2 className="font-semibold text-slate-950">Repository status</h2><p className="text-sm text-slate-500">Current repository inventory.</p></div><div className="grid gap-3 sm:grid-cols-2"><Info label="Status" value="Connected" /><Info label="Remote" value={data.repository.remote} mono /><Info label="Teams" value={data.repository.teamCount} /><Info label="Workflows" value={data.repository.workflowCount} /></div><div className="mt-5 flex items-center gap-2 text-xs text-slate-400"><CheckCircle2 className="h-4 w-4 text-emerald-500" /> Last checked {new Date(data.repository.syncedAt).toLocaleString()}</div></section><section className="cm-card p-5"><div className="mb-4"><h2 className="font-semibold text-slate-950">Recent activity</h2><p className="text-sm text-slate-500">Latest audit events.</p></div><div className="divide-y divide-slate-100">{data.recentActivity.length === 0 ? <Empty text="No activity recorded yet." /> : data.recentActivity.map((row: any) => <div key={row.id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-medium text-slate-800">{row.action}</p><p className="text-xs text-slate-500">{row.actorEmail}{row.workflowId ? ` · ${row.workflowId}` : ''}</p></div><span className="shrink-0 text-xs text-slate-400">{new Date(row.createdAt).toLocaleString()}</span></div>)}</div></section></div></> }

function WorkflowsPage({ navigate }: PageProps) { const [q, setQ] = useState(''); const [data, setData] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = () => { setLoading(true); api.workflows(q).then(setData).catch((e) => setError(e.message)).finally(() => setLoading(false)) }; useEffect(load, []); return <><PageHeader title="Workflows" description="Browse workflow branches grouped by their metadata team folder." action={<div className="flex gap-2"><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input className="cm-input pl-9 sm:w-72" value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load()} placeholder="Search workflows..." /></div><button className="cm-btn-secondary" onClick={load}>Search</button></div>} />{error && <ErrorBox message={error} onRetry={load} />}{loading ? <Loading /> : <section className="cm-card overflow-hidden"><div className="divide-y divide-slate-100">{data?.data.length === 0 ? <Empty text="No workflows found." /> : data.data.map((team: any) => <div key={team.name}><div className="flex items-center justify-between bg-slate-50 px-5 py-3"><div className="flex items-center gap-2 text-sm font-semibold text-slate-700"><Users className="h-4 w-4 text-slate-400" />{team.name}</div><span className="cm-badge bg-white text-slate-500 ring-1 ring-slate-200">{team.workflowCount} workflow{team.workflowCount === 1 ? '' : 's'}</span></div>{team.workflows.map((w: BranchInfo) => <button key={w.branchName} onClick={() => navigate(`/mappings/${w.workflowId}`)} className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left hover:bg-slate-50"><div className="min-w-0"><div className="flex items-center gap-2"><Workflow className="h-4 w-4 shrink-0 text-slate-400" /><span className="truncate font-medium text-slate-900">{w.workflowName || w.workflowId}</span></div><p className="mt-1 pl-6 font-mono text-xs text-slate-400">{w.branchName}</p></div><div className="flex shrink-0 items-center gap-4"><span className="hidden font-mono text-xs text-slate-400 md:block">{w.headSha}</span><span className="cm-badge bg-emerald-50 text-emerald-700">{w.status}</span><ArrowRight className="h-4 w-4 text-slate-300" /></div></button>)}</div>)}</div></section>}</> }

function MappingsPage({ navigate }: PageProps) { const [q, setQ] = useState(''); const [data, setData] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = () => { setLoading(true); api.mappings(q).then(setData).catch((e) => setError(e.message)).finally(() => setLoading(false)) }; useEffect(load, []); return <><PageHeader title="Mappings" description="Review credential mapping coverage for workflow branches." action={<div className="flex gap-2"><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input className="cm-input pl-9 sm:w-72" value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load()} placeholder="Search mappings..." /></div><button className="cm-btn-secondary" onClick={load}>Search</button></div>} />{error && <ErrorBox message={error} onRetry={load} />}{loading ? <Loading /> : <section className="cm-card overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Workflow</th><th className="px-5 py-3">Team</th><th className="px-5 py-3">Entries</th><th className="px-5 py-3">Mapping</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{data?.data.map((w: any) => <tr key={w.branchName} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-medium text-slate-900">{w.workflowName || w.workflowId}</p><p className="font-mono text-xs text-slate-400">{w.workflowId}</p></td><td className="px-5 py-4 text-slate-600">{w.teamFolder || 'Unassigned'}</td><td className="px-5 py-4 text-slate-600">{w.entryCount}</td><td className="px-5 py-4"><span className={`cm-badge ${w.mappingExists ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{w.mappingExists ? 'Configured' : 'Not configured'}</span></td><td className="px-5 py-4 text-right"><button className="cm-btn-primary" onClick={() => navigate(`/mappings/${w.workflowId}`)}>Open</button></td></tr>)}{data?.data.length === 0 && <tr><td colSpan={5}><Empty text="No mappings found." /></td></tr>}</tbody></table></div></section>}</> }

function DraftsPage({ navigate }: PageProps) { const [data, setData] = useState<any>(null); const [error, setError] = useState(''); useEffect(() => { api.drafts().then(setData).catch((e) => setError(e.message)) }, []); return <><PageHeader title="Drafts" description="Credential mapping changes saved before commit." />{error ? <ErrorBox message={error} /> : !data ? <Loading /> : <section className="cm-card overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Workflow</th><th className="px-5 py-3">Version</th><th className="px-5 py-3">Updated by</th><th className="px-5 py-3">Updated</th><th className="px-5 py-3">Status</th><th /></tr></thead><tbody className="divide-y divide-slate-100">{data.data.map((d: any) => <tr key={d.draftId}><td className="px-5 py-4 font-medium text-slate-900">{d.workflowId}</td><td className="px-5 py-4">v{d.version}</td><td className="px-5 py-4">{d.updatedBy}</td><td className="px-5 py-4 text-slate-500">{new Date(d.updatedAt).toLocaleString()}</td><td className="px-5 py-4"><span className="cm-badge bg-blue-50 text-blue-700">{d.status}</span></td><td className="px-5 py-4 text-right"><button className="cm-btn-secondary" onClick={() => navigate(`/mappings/${d.workflowId}`)}>Open</button></td></tr>)}{data.data.length === 0 && <tr><td colSpan={6}><Empty text="No drafts available." /></td></tr>}</tbody></table></div></section>}</> }

function AuditPage() { const [data, setData] = useState<any>(null); useEffect(() => { api.listAudit().then(setData) }, []); return <><PageHeader title="Audit Logs" description="Track mapping, synchronization, validation, and commit activity." />{!data ? <Loading /> : <section className="cm-card overflow-hidden"><div className="divide-y divide-slate-100">{data.data.map((row: any) => <div key={row.id} className="grid gap-2 px-5 py-4 md:grid-cols-[1fr_1.5fr_auto]"><div><span className="cm-badge bg-slate-100 text-slate-700">{row.action}</span></div><div><p className="text-sm font-medium text-slate-800">{row.actorEmail}</p><p className="font-mono text-xs text-slate-400">{row.workflowId || row.branchName || 'System event'}</p></div><p className="text-xs text-slate-400 md:text-right">{new Date(row.createdAt).toLocaleString()}</p></div>)}{data.data.length === 0 && <Empty text="No audit events recorded yet." />}</div></section>}</> }

function RepositoryPage() { const [data, setData] = useState<any>(null); const [error, setError] = useState(''); const load = () => api.repository().then(setData).catch((e) => setError(e.message)); useEffect(load, []); return <><PageHeader title="Repository" description="Git repository connection and synchronization inventory." action={<button className="cm-btn-secondary" onClick={load}><RefreshCcw className="h-4 w-4" /> Refresh</button>} />{error ? <ErrorBox message={error} onRetry={load} /> : !data ? <Loading /> : <div className="grid gap-6 lg:grid-cols-2"><section className="cm-card p-6"><div className="flex items-center gap-3"><div className="rounded-lg bg-emerald-50 p-2.5 text-emerald-600"><Server className="h-5 w-5" /></div><div><h2 className="font-semibold">Repository connection</h2><p className="text-sm text-slate-500">Remote: {data.remote}</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Info label="Status" value={data.status} /><Info label="Remote" value={data.remote} mono /><Info label="Workflow branches" value={data.workflowBranchCount} /><Info label="Teams" value={data.teamCount} /></div></section></div>}</> }

export default function App() { const [user, setUser] = useState<CurrentUser | null>(null); const [sessionLoading, setSessionLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [path, setPath] = useState(() => window.location.pathname === '/' ? '/dashboard' : window.location.pathname); const [selectedBranch, setSelectedBranch] = useState<BranchInfo | null>(null); const navigate = (next: string) => { window.history.pushState({}, '', next); setPath(next) }; useEffect(() => { const handler = () => setPath(window.location.pathname); window.addEventListener('popstate', handler); return () => window.removeEventListener('popstate', handler) }, []); useEffect(() => { api.me().then((res) => { if (!res.authenticated || !res.user) { api.login(); return } setUser(res.user) }).catch((err) => setError(err?.message ?? 'Gagal memuat session login.')).finally(() => setSessionLoading(false)) }, []); useEffect(() => { if (path.startsWith('/mappings/') && !selectedBranch) { const id = decodeURIComponent(path.split('/')[2] || ''); api.mappings(id).then((res) => { const found = res.data.find((item) => item.workflowId === id); if (found) setSelectedBranch(found) }).catch(() => {}) } }, [path, selectedBranch]); if (sessionLoading) return <Loading />; if (error) return <div className="flex min-h-screen items-center justify-center"><ErrorBox message={error} onRetry={() => api.login()} /></div>; if (!user) return <Loading />; const detail = path.startsWith('/mappings/') && selectedBranch; return <div className="min-h-screen bg-slate-50"><Header user={user} /><div className="flex min-h-[calc(100vh-4rem)]"><Sidebar path={path} onNavigate={(next) => { setSelectedBranch(null); navigate(next) }} /><main className="min-w-0 flex-1 px-5 py-7 lg:px-8">{detail ? <MappingEditor branch={selectedBranch} onBack={() => { setSelectedBranch(null); navigate('/mappings') }} /> : path === '/workflows' ? <WorkflowsPage navigate={navigate} /> : path === '/mappings' ? <MappingsPage navigate={navigate} /> : path === '/drafts' ? <DraftsPage navigate={navigate} /> : path === '/audit' ? <AuditPage /> : path === '/repository' ? <RepositoryPage /> : <DashboardPage />}</main></div></div> }
